# Generated by Django 3.2.8 on 2023-08-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarouselHeader',
            new_name='Carousel',
        ),
    ]
