# Generated by Django 3.2.8 on 2023-12-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.IntegerField(choices=[('lifestyle', 'Lifestyle'), ('code', 'Code')], default=0),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.IntegerField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default=0),
        ),
    ]
