# Generated by Django 3.2.8 on 2024-01-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20231215_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='url_path',
            field=models.URLField(default=0),
        ),
    ]
