# Generated by Django 3.2.8 on 2024-01-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_carousel_url_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='url_path',
        ),
        migrations.AddField(
            model_name='carousel',
            name='route',
            field=models.IntegerField(choices=[(0, "{% url 'homepage' %}"), (1, "{% url 'code' %}"), (2, "{% url 'lifestyle' %}")], default=0),
        ),
    ]
