# Generated by Django 3.2.8 on 2024-01-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20240125_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='route',
            field=models.IntegerField(choices=[(0, "'homepage'"), (1, "'lifestyle'"), (2, "'code'")], default=0),
        ),
    ]
