# Generated by Django 3.2.8 on 2024-01-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_carousel_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='route',
            field=models.IntegerField(choices=[(0, "{% url 'homepage' %}"), (1, "{% url 'lifestyle' %}"), (2, "{% url 'code' %}")], default=0),
        ),
    ]
