# Generated by Django 3.2.8 on 2024-01-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_carousel_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='route',
            field=models.CharField(max_length=100),
        ),
    ]
