# Generated by Django 3.2.8 on 2024-02-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_carousel_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='sub_title',
            field=models.CharField(blank=0, max_length=100),
        ),
    ]
