# Generated by Django 3.2.8 on 2024-02-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_carousel_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='sub_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
