# Generated by Django 3.2.8 on 2024-04-25 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_rename_images_image_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='BlogImages',
        ),
    ]
