# Generated by Django 3.2.8 on 2025-01-30 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_rename_image_blogimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogImages',
        ),
    ]
