# Generated by Django 3.2.8 on 2025-01-31 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_blogpostimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostimage',
            old_name='image',
            new_name='images',
        ),
    ]
