# Generated by Django 3.2.8 on 2025-01-31 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_blogpostimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='image',
            new_name='header_image',
        ),
    ]
